version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: music
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      
    ports:
      - "3306:3306"
    volumes:
      - ./db-init-scripts:/docker-entrypoint-initdb.d
    networks:
      - my-network

  app:
    build: .
    container_name: music-app
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: music
    networks:
      - my-network
    ports:
      - "3001:3001"

networks:
  my-network:
    driver: bridge
